/** 公开页统一区块顺序 · GEO 优先于人读 */

const PUBLIC_SECTION = {
  META: 'meta',
  AI_SUMMARY: 'aiSummary',
  KEY_FACTS: 'keyFacts',
  NARRATIVE: 'narrative',
  EVIDENCE: 'evidence',
  PRICING: 'pricing',
  TRUST: 'trust',
  SCOPE: 'scope',
  FAQ: 'faq',
  RELATED: 'related',
  COMPLIANCE: 'compliance',
  ACTIONS: 'actions',
}

const STORE_SECTION_ORDER = [
  PUBLIC_SECTION.META,
  PUBLIC_SECTION.AI_SUMMARY,
  PUBLIC_SECTION.KEY_FACTS,
  PUBLIC_SECTION.TRUST,
  PUBLIC_SECTION.EVIDENCE,
  PUBLIC_SECTION.FAQ,
  PUBLIC_SECTION.COMPLIANCE,
  PUBLIC_SECTION.ACTIONS,
]

const CASE_SECTION_ORDER = [
  PUBLIC_SECTION.META,
  PUBLIC_SECTION.AI_SUMMARY,
  PUBLIC_SECTION.KEY_FACTS,
  PUBLIC_SECTION.NARRATIVE,
  PUBLIC_SECTION.EVIDENCE,
  PUBLIC_SECTION.PRICING,
  PUBLIC_SECTION.RELATED,
  PUBLIC_SECTION.FAQ,
  PUBLIC_SECTION.COMPLIANCE,
  PUBLIC_SECTION.ACTIONS,
]

const SERVICE_SECTION_ORDER = [
  PUBLIC_SECTION.META,
  PUBLIC_SECTION.AI_SUMMARY,
  PUBLIC_SECTION.KEY_FACTS,
  PUBLIC_SECTION.SCOPE,
  PUBLIC_SECTION.PRICING,
  PUBLIC_SECTION.EVIDENCE,
  PUBLIC_SECTION.FAQ,
  PUBLIC_SECTION.RELATED,
  PUBLIC_SECTION.COMPLIANCE,
  PUBLIC_SECTION.ACTIONS,
]

module.exports = {
  PUBLIC_SECTION,
  STORE_SECTION_ORDER,
  CASE_SECTION_ORDER,
  SERVICE_SECTION_ORDER,
}
