-- GEO-TOPIC-A01 · geo_pages 意图专题表
CREATE TABLE `geo_pages` (
  `id` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `title` VARCHAR(191) NOT NULL DEFAULT '',
  `summary` TEXT NOT NULL,
  `cover_image` VARCHAR(512) NOT NULL DEFAULT '',
  `page_type` VARCHAR(32) NOT NULL DEFAULT 'city_service',
  `city` VARCHAR(191) NOT NULL DEFAULT '',
  `service_id` VARCHAR(191) NOT NULL DEFAULT '',
  `fault_tag` VARCHAR(191) NOT NULL DEFAULT '',
  `vehicle_series` VARCHAR(191) NOT NULL DEFAULT '',
  `keywords_json` JSON NOT NULL,
  `scenarios_json` JSON NOT NULL,
  `price_factors_json` JSON NOT NULL,
  `faq_json` JSON NOT NULL,
  `faq_links_json` JSON NOT NULL,
  `related_case_ids_json` JSON NOT NULL,
  `related_store_ids_json` JSON NOT NULL,
  `primary_store_id` VARCHAR(191) NOT NULL DEFAULT '',
  `related_service_id` VARCHAR(191) NOT NULL DEFAULT '',
  `seo_title` VARCHAR(160) NOT NULL DEFAULT '',
  `seo_description` VARCHAR(300) NOT NULL DEFAULT '',
  `ai_summary` TEXT NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
  `published_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `geo_pages_slug_key`(`slug`),
  INDEX `geo_pages_status_idx`(`status`),
  INDEX `geo_pages_city_idx`(`city`),
  INDEX `geo_pages_page_type_idx`(`page_type`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
